name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # 指定使用的公共运行器
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run a script
        run: echo "Hello, World!"

      - name: manual-approve
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1,user2,org-team1
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
      additional-denied-words: ''
