name: test-api

on:
  pull_request:
    types: [closed]

jobs:
  create_issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue using GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{"title": "New Issue for PR #${{ github.event.number }}", "body": "This issue was created automatically after merging PR #${{ github.event.number }}."}'
