name: test-tmate
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1
      
    - name: Debuging...
      run: echo "This is a debug step"
